// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udjtidzinaxqbjcjxzbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkanRpZHppbmF4cWJqY2p4emJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTA2MjEsImV4cCI6MjA3MDg4NjYyMX0.sv9vAaap1EEwl4Ct_E9XxUw9dViyV9KKp9u2RZFrf4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});